# GitHub Action for generating a contribution graph with a snake animation.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours and can be triggered manually.
on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

# The sequence of jobs in this workflow
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: "lalitk533784" # Replace with your GitHub username
          outputs: |
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Show the status of the repository for debugging
      - name: Show build status
        run: git status

      # Step 4: Push new files to the output branch
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output # The branch where output files are stored
          build_dir: dist
          commit_message: "Update snake animations"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
